_CATEGORY_MAPPING = {
    "Subscriptions": "Expenses:DIS:Subscriptions",
    "Banking": "Expenses:LIV:Banking",
    "Taxes": "Expenses:LIV:Taxes",
    "Utilities": "Expenses:LIV:Utilities",
    "Rent": "Expenses:LIV:Rent",
    "Eating Out": "Expenses:DIS:EatingOut",
    "Fitness & Wellness": "Expenses:QOL:FitnessAndWellness",
    "Social Security": "Assets:SocialSecurity",
    "Healthcare": "Expenses:LIV:Healthcare",
    "Insurances": "Expenses:DIS:Insurances",
    "Transport": "Expenses:LIV:Transport",
    "Ready to Assign": "Income:BankOfItaly",
    "Gifts": "Expenses:QOL:Gifts",
    "Entertainment": "Expenses:QOL:Entertainment",
    "Home": "Expenses:LIV:Home",
    "Multimedia": "Expenses:DIS:Multimedia",
    "Trading": "Expenses:DIS:Trading",
    "Groceries": "Expenses:LIV:Groceries",
    "Clothing": "Expenses:LIV:Clothing",
    "Personal Care": "Expenses:DIS:PersonalCare",
    "Vehicles Maintenance": "Expenses:VEH:Maintenance",
    "Travel & Vacation": "Expenses:QOL:TravelsAndVacations",
    "Electronics": "Expenses:DIS:Electronics",
    "Partying": "Expenses:DIS:Partying",
    "Vehicles Insurance": "Expenses:VEH:Insurance",
    "Fines": "Expenses:LIV:Fines",
    "Giving": "Expenses:QOL:Giving",
    "Education": "Expenses:QOL:Education",
    "Side Projects": "Expenses:DIS:SideProjects",
}

def map_category(category: str) -> str:
    return _CATEGORY_MAPPING[category]
