_CATEGORY_MAPPING = {
    "Subscriptions": "Expenses:Discretionary:Subscriptions",
    "Banking": "Expenses:Living:Banking",
    "Taxes": "Expenses:Living:Taxes",
    "Utilities": "Expenses:Living:Utilities",
    "Rent": "Expenses:Living:Rent",
    "Eating Out": "Expenses:Discretionary:EatingOut",
    "Fitness & Wellness": "Expenses:QualityOfLife:FitnessAndWellness",
    "Social Security": "Assets:SocialSecurity",
    "Healthcare": "Expenses:Living:Healthcare",
    "Insurances": "Expenses:Discretionary:Insurances",
    "Transport": "Expenses:Living:Transport",
    "Ready to Assign": "Income:BankOfItaly",
    "Gifts": "Expenses:QualityOfLife:Gifts",
    "Entertainment": "Expenses:QualityOfLife:Entertainment",
    "Home": "Expenses:Living:Home",
    "Multimedia": "Expenses:Discretionary:Multimedia",
    "Trading": "Expenses:Discretionary:Trading",
    "Groceries": "Expenses:Living:Groceries",
    "Clothing": "Expenses:Living:Clothing",
    "Personal Care": "Expenses:Discretionary:PersonalCare",
    "Vehicles Maintenance": "Expenses:Vehicles:Maintenance",
    "Travel & Vacation": "Expenses:QualityOfLife:TravelsAndVacations",
    "Electronics": "Expenses:Discretionary:Electronics",
    "Partying": "Expenses:Discretionary:Partying",
    "Vehicles Insurance": "Expenses:Vehicles:Insurance",
    "Fines": "Expenses:Living:Fines",
    "Giving": "Expenses:QualityOfLife:Giving",
    "Education": "Expenses:QualityOfLife:Education",
    "Side Projects": "Expenses:Discretionary:SideProjects",
}

def map_category(category: str) -> str:
    return _CATEGORY_MAPPING[category]
